### ISSUE TITLE
Incompatibility using pretrained models of deepvoice3 after update 

### ISSUE THREAD

**Issue by TheFlash10** [PaddlePaddle/Parakeet#14]
Hey
I recently trained a deepvoice3 model before there were new changes committed in the folder. But after updating my repo, i was not able to use the pretrained models.
I got this error

```
  File "train.py", line 147, in <module>
    optim.minimize(l)
"Optimizer set error, {} should in state dict".format( var_name )
AssertionError: Optimizer set error, embedding_0.w_0_moment1_0 should in state dict
```
If we start training from scratch, then this problem does not come.

Can you suggest what can be the issue in incorporating the models we trained before the update was done for deepvoice3 ?

Thanks

**Comment by iclementine** [comment]
This is cased by an update of the optimizer. The naming rule of variables within optimizer states has been changed since paddlepaddle 1.8. So it is in compatable with the optimizer states saved with paddlepaddle 1.7 or earlier versions.

So may be paddlepaddle has been updated since then?

An temporary solution is to ignore the optimizer state and just load the parameters of the model. It can be done by enaming the optimizer or moving it to somewhere else.
